# Generated by Django 6.0a1 on 2025-11-23 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="Enter 10 digit mobile number.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                6, message="Password must be at least 8 characters."
                            )
                        ],
                    ),
                ),
                ("adress", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("working", "Working"),
                            ("family", "Family"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        choices=[
                            ("poster", "Poster"),
                            ("social_media", "Social Media"),
                            ("friends", "Friends"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
