# Generated by Django 6.0a1 on 2025-11-24 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="Enter 10 digit mobile number.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                6, message="Password must be at least 8 characters."
                            )
                        ],
                    ),
                ),
                ("pincode", models.CharField(max_length=6)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=40, unique=True)),
                (
                    "providers",
                    models.ManyToManyField(
                        blank=True, related_name="services", to="core.serviceprovider"
                    ),
                ),
            ],
        ),
    ]
