# Generated by Django 6.0a1 on 2025-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_serviceprovider_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="reference",
        ),
        migrations.AddField(
            model_name="users",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.CharField(
                choices=[("provider", "Provider"), ("user", "USER")], max_length=10
            ),
        ),
    ]
