# Generated by Django 5.2.6 on 2025-11-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_users_reference_users_gender_users_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='pincode',
        ),
    ]
